version: "3"
services:
  product-app:
    image: cmabdullah21/spring-boot-docker-v04
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

  mysqldb:
    image:  mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'productdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user-cm'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'rootcm'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootcm'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db-v2:/var/lib/mysql
# Names our volume
volumes:
  my-db-v2:
# docker build -t cmabdullah21/spring-boot-docker-v04 --progress=plain .
# docker-compose -f docker-compose.yml up