apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: cmabdullah21/spring-boot-docker-v06
      ports:
        - containerPort: 8080
